services:
  api:
    build: .
    container_name: iruyan-api
    ports:
      - "8080:8080"
    volumes:
      - .:/app  # ホストのソースコードをコンテナ内にマウントしてホットリロード対応
    environment:
      - GO_ENV=development
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    container_name: postgres-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: exampledb
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
